version: '3.3'

services:

  database:
    image: postgres:14.0-alpine
    env_file:
      - ./.env

  parser:
    build: ../news_parser/
    depends_on:
      - database
    env_file:
      - ./.env
